# Generated by Django 4.2 on 2023-04-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subscribers',
            field=models.ManyToManyField(to='tasks.employee', verbose_name='Подписчики на рассылку по задаче'),
        ),
    ]
