# Generated by Django 4.2 on 2023-04-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_files_url_alter_task_result_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstage',
            name='alias',
            field=models.CharField(null=True, verbose_name='Альяс'),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='alias',
            field=models.CharField(null=True, verbose_name='Альяс'),
        ),
    ]
