# Generated by Django 4.2 on 2023-04-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_employee_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='btrx_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Id сотрудника в Bitrix'),
        ),
    ]
