# Generated by Django 4.2 on 2023-04-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_comment_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AlterField(
            model_name='task',
            name='bitrix_id',
            field=models.PositiveIntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='ID задачи в Bitrix'),
        ),
    ]
